### ISSUE TITLE
Qmin is off by sqrt(gamma)

### ISSUE THREAD

**Issue by trquinn** [ibackus/diskpy#21]
Around line 265 of sigma_profile.py there is:
    # Calculate Q
    Q = np.sqrt(Mstar*kB*T(R)/(G*m*R**3))/(np.pi*sigma)
    Q.convert_units('1')

Should there be a "gamma" inside that np.sqrt()?

**Comment by ibackus** [comment]
This is correct in the isothermal case, however we are not always using isothermal, so I should fix that.
